/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HolidayPackagesRouteImport } from './routes/holiday-packages'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as HolidayPackagesIndexRouteImport } from './routes/holiday-packages.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesVisaRouteImport } from './routes/services.visa'
import { Route as ServicesInsuranceRouteImport } from './routes/services.insurance'
import { Route as ServicesHotelsRouteImport } from './routes/services.hotels'
import { Route as ServicesForexRouteImport } from './routes/services.forex'
import { Route as ServicesFlightsRouteImport } from './routes/services.flights'
import { Route as ServicesCabsRouteImport } from './routes/services.cabs'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminDestinationsRouteImport } from './routes/admin.destinations'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as HolidayPackagesInternationalIndexRouteImport } from './routes/holiday-packages.international.index'
import { Route as HolidayPackagesDomesticIndexRouteImport } from './routes/holiday-packages.domestic.index'
import { Route as HolidayPackagesTourTypeRouteImport } from './routes/holiday-packages.tour.$type'
import { Route as HolidayPackagesPackageSlugRouteImport } from './routes/holiday-packages.package.$slug'
import { Route as HolidayPackagesInternationalCountryRouteImport } from './routes/holiday-packages.international.$country'
import { Route as HolidayPackagesDomesticStateRouteImport } from './routes/holiday-packages.domestic.$state'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidayPackagesRoute = HolidayPackagesRouteImport.update({
  id: '/holiday-packages',
  path: '/holiday-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidayPackagesIndexRoute = HolidayPackagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HolidayPackagesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesVisaRoute = ServicesVisaRouteImport.update({
  id: '/services/visa',
  path: '/services/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInsuranceRoute = ServicesInsuranceRouteImport.update({
  id: '/services/insurance',
  path: '/services/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHotelsRoute = ServicesHotelsRouteImport.update({
  id: '/services/hotels',
  path: '/services/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesForexRoute = ServicesForexRouteImport.update({
  id: '/services/forex',
  path: '/services/forex',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFlightsRoute = ServicesFlightsRouteImport.update({
  id: '/services/flights',
  path: '/services/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCabsRoute = ServicesCabsRouteImport.update({
  id: '/services/cabs',
  path: '/services/cabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinationsRoute = AdminDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const HolidayPackagesInternationalIndexRoute =
  HolidayPackagesInternationalIndexRouteImport.update({
    id: '/international/',
    path: '/international/',
    getParentRoute: () => HolidayPackagesRoute,
  } as any)
const HolidayPackagesDomesticIndexRoute =
  HolidayPackagesDomesticIndexRouteImport.update({
    id: '/domestic/',
    path: '/domestic/',
    getParentRoute: () => HolidayPackagesRoute,
  } as any)
const HolidayPackagesTourTypeRoute = HolidayPackagesTourTypeRouteImport.update({
  id: '/tour/$type',
  path: '/tour/$type',
  getParentRoute: () => HolidayPackagesRoute,
} as any)
const HolidayPackagesPackageSlugRoute =
  HolidayPackagesPackageSlugRouteImport.update({
    id: '/package/$slug',
    path: '/package/$slug',
    getParentRoute: () => HolidayPackagesRoute,
  } as any)
const HolidayPackagesInternationalCountryRoute =
  HolidayPackagesInternationalCountryRouteImport.update({
    id: '/international/$country',
    path: '/international/$country',
    getParentRoute: () => HolidayPackagesRoute,
  } as any)
const HolidayPackagesDomesticStateRoute =
  HolidayPackagesDomesticStateRouteImport.update({
    id: '/domestic/$state',
    path: '/domestic/$state',
    getParentRoute: () => HolidayPackagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/holiday-packages': typeof HolidayPackagesRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/cabs': typeof ServicesCabsRoute
  '/services/flights': typeof ServicesFlightsRoute
  '/services/forex': typeof ServicesForexRoute
  '/services/hotels': typeof ServicesHotelsRoute
  '/services/insurance': typeof ServicesInsuranceRoute
  '/services/visa': typeof ServicesVisaRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/holiday-packages/': typeof HolidayPackagesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/holiday-packages/domestic/$state': typeof HolidayPackagesDomesticStateRoute
  '/holiday-packages/international/$country': typeof HolidayPackagesInternationalCountryRoute
  '/holiday-packages/package/$slug': typeof HolidayPackagesPackageSlugRoute
  '/holiday-packages/tour/$type': typeof HolidayPackagesTourTypeRoute
  '/holiday-packages/domestic/': typeof HolidayPackagesDomesticIndexRoute
  '/holiday-packages/international/': typeof HolidayPackagesInternationalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/cabs': typeof ServicesCabsRoute
  '/services/flights': typeof ServicesFlightsRoute
  '/services/forex': typeof ServicesForexRoute
  '/services/hotels': typeof ServicesHotelsRoute
  '/services/insurance': typeof ServicesInsuranceRoute
  '/services/visa': typeof ServicesVisaRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/holiday-packages': typeof HolidayPackagesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/holiday-packages/domestic/$state': typeof HolidayPackagesDomesticStateRoute
  '/holiday-packages/international/$country': typeof HolidayPackagesInternationalCountryRoute
  '/holiday-packages/package/$slug': typeof HolidayPackagesPackageSlugRoute
  '/holiday-packages/tour/$type': typeof HolidayPackagesTourTypeRoute
  '/holiday-packages/domestic': typeof HolidayPackagesDomesticIndexRoute
  '/holiday-packages/international': typeof HolidayPackagesInternationalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/holiday-packages': typeof HolidayPackagesRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/cabs': typeof ServicesCabsRoute
  '/services/flights': typeof ServicesFlightsRoute
  '/services/forex': typeof ServicesForexRoute
  '/services/hotels': typeof ServicesHotelsRoute
  '/services/insurance': typeof ServicesInsuranceRoute
  '/services/visa': typeof ServicesVisaRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/holiday-packages/': typeof HolidayPackagesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/holiday-packages/domestic/$state': typeof HolidayPackagesDomesticStateRoute
  '/holiday-packages/international/$country': typeof HolidayPackagesInternationalCountryRoute
  '/holiday-packages/package/$slug': typeof HolidayPackagesPackageSlugRoute
  '/holiday-packages/tour/$type': typeof HolidayPackagesTourTypeRoute
  '/holiday-packages/domestic/': typeof HolidayPackagesDomesticIndexRoute
  '/holiday-packages/international/': typeof HolidayPackagesInternationalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/corporate'
    | '/faq'
    | '/gallery'
    | '/holiday-packages'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/admin/blog'
    | '/admin/destinations'
    | '/admin/faqs'
    | '/admin/forgot-password'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/packages'
    | '/admin/pages'
    | '/admin/reset-password'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/services/$slug'
    | '/services/cabs'
    | '/services/flights'
    | '/services/forex'
    | '/services/hotels'
    | '/services/insurance'
    | '/services/visa'
    | '/admin/'
    | '/blog/'
    | '/holiday-packages/'
    | '/services/'
    | '/holiday-packages/domestic/$state'
    | '/holiday-packages/international/$country'
    | '/holiday-packages/package/$slug'
    | '/holiday-packages/tour/$type'
    | '/holiday-packages/domestic/'
    | '/holiday-packages/international/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/corporate'
    | '/faq'
    | '/gallery'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/admin/blog'
    | '/admin/destinations'
    | '/admin/faqs'
    | '/admin/forgot-password'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/packages'
    | '/admin/pages'
    | '/admin/reset-password'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/services/$slug'
    | '/services/cabs'
    | '/services/flights'
    | '/services/forex'
    | '/services/hotels'
    | '/services/insurance'
    | '/services/visa'
    | '/admin'
    | '/blog'
    | '/holiday-packages'
    | '/services'
    | '/holiday-packages/domestic/$state'
    | '/holiday-packages/international/$country'
    | '/holiday-packages/package/$slug'
    | '/holiday-packages/tour/$type'
    | '/holiday-packages/domestic'
    | '/holiday-packages/international'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/corporate'
    | '/faq'
    | '/gallery'
    | '/holiday-packages'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/admin/blog'
    | '/admin/destinations'
    | '/admin/faqs'
    | '/admin/forgot-password'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/packages'
    | '/admin/pages'
    | '/admin/reset-password'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/services/$slug'
    | '/services/cabs'
    | '/services/flights'
    | '/services/forex'
    | '/services/hotels'
    | '/services/insurance'
    | '/services/visa'
    | '/admin/'
    | '/blog/'
    | '/holiday-packages/'
    | '/services/'
    | '/holiday-packages/domestic/$state'
    | '/holiday-packages/international/$country'
    | '/holiday-packages/package/$slug'
    | '/holiday-packages/tour/$type'
    | '/holiday-packages/domestic/'
    | '/holiday-packages/international/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  HolidayPackagesRoute: typeof HolidayPackagesRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesCabsRoute: typeof ServicesCabsRoute
  ServicesFlightsRoute: typeof ServicesFlightsRoute
  ServicesForexRoute: typeof ServicesForexRoute
  ServicesHotelsRoute: typeof ServicesHotelsRoute
  ServicesInsuranceRoute: typeof ServicesInsuranceRoute
  ServicesVisaRoute: typeof ServicesVisaRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holiday-packages': {
      id: '/holiday-packages'
      path: '/holiday-packages'
      fullPath: '/holiday-packages'
      preLoaderRoute: typeof HolidayPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holiday-packages/': {
      id: '/holiday-packages/'
      path: '/'
      fullPath: '/holiday-packages/'
      preLoaderRoute: typeof HolidayPackagesIndexRouteImport
      parentRoute: typeof HolidayPackagesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/visa': {
      id: '/services/visa'
      path: '/services/visa'
      fullPath: '/services/visa'
      preLoaderRoute: typeof ServicesVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/insurance': {
      id: '/services/insurance'
      path: '/services/insurance'
      fullPath: '/services/insurance'
      preLoaderRoute: typeof ServicesInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hotels': {
      id: '/services/hotels'
      path: '/services/hotels'
      fullPath: '/services/hotels'
      preLoaderRoute: typeof ServicesHotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/forex': {
      id: '/services/forex'
      path: '/services/forex'
      fullPath: '/services/forex'
      preLoaderRoute: typeof ServicesForexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/flights': {
      id: '/services/flights'
      path: '/services/flights'
      fullPath: '/services/flights'
      preLoaderRoute: typeof ServicesFlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cabs': {
      id: '/services/cabs'
      path: '/services/cabs'
      fullPath: '/services/cabs'
      preLoaderRoute: typeof ServicesCabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinations': {
      id: '/admin/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminDestinationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/holiday-packages/international/': {
      id: '/holiday-packages/international/'
      path: '/international'
      fullPath: '/holiday-packages/international/'
      preLoaderRoute: typeof HolidayPackagesInternationalIndexRouteImport
      parentRoute: typeof HolidayPackagesRoute
    }
    '/holiday-packages/domestic/': {
      id: '/holiday-packages/domestic/'
      path: '/domestic'
      fullPath: '/holiday-packages/domestic/'
      preLoaderRoute: typeof HolidayPackagesDomesticIndexRouteImport
      parentRoute: typeof HolidayPackagesRoute
    }
    '/holiday-packages/tour/$type': {
      id: '/holiday-packages/tour/$type'
      path: '/tour/$type'
      fullPath: '/holiday-packages/tour/$type'
      preLoaderRoute: typeof HolidayPackagesTourTypeRouteImport
      parentRoute: typeof HolidayPackagesRoute
    }
    '/holiday-packages/package/$slug': {
      id: '/holiday-packages/package/$slug'
      path: '/package/$slug'
      fullPath: '/holiday-packages/package/$slug'
      preLoaderRoute: typeof HolidayPackagesPackageSlugRouteImport
      parentRoute: typeof HolidayPackagesRoute
    }
    '/holiday-packages/international/$country': {
      id: '/holiday-packages/international/$country'
      path: '/international/$country'
      fullPath: '/holiday-packages/international/$country'
      preLoaderRoute: typeof HolidayPackagesInternationalCountryRouteImport
      parentRoute: typeof HolidayPackagesRoute
    }
    '/holiday-packages/domestic/$state': {
      id: '/holiday-packages/domestic/$state'
      path: '/domestic/$state'
      fullPath: '/holiday-packages/domestic/$state'
      preLoaderRoute: typeof HolidayPackagesDomesticStateRouteImport
      parentRoute: typeof HolidayPackagesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminDestinationsRoute: typeof AdminDestinationsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminDestinationsRoute: AdminDestinationsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HolidayPackagesRouteChildren {
  HolidayPackagesIndexRoute: typeof HolidayPackagesIndexRoute
  HolidayPackagesDomesticStateRoute: typeof HolidayPackagesDomesticStateRoute
  HolidayPackagesInternationalCountryRoute: typeof HolidayPackagesInternationalCountryRoute
  HolidayPackagesPackageSlugRoute: typeof HolidayPackagesPackageSlugRoute
  HolidayPackagesTourTypeRoute: typeof HolidayPackagesTourTypeRoute
  HolidayPackagesDomesticIndexRoute: typeof HolidayPackagesDomesticIndexRoute
  HolidayPackagesInternationalIndexRoute: typeof HolidayPackagesInternationalIndexRoute
}

const HolidayPackagesRouteChildren: HolidayPackagesRouteChildren = {
  HolidayPackagesIndexRoute: HolidayPackagesIndexRoute,
  HolidayPackagesDomesticStateRoute: HolidayPackagesDomesticStateRoute,
  HolidayPackagesInternationalCountryRoute:
    HolidayPackagesInternationalCountryRoute,
  HolidayPackagesPackageSlugRoute: HolidayPackagesPackageSlugRoute,
  HolidayPackagesTourTypeRoute: HolidayPackagesTourTypeRoute,
  HolidayPackagesDomesticIndexRoute: HolidayPackagesDomesticIndexRoute,
  HolidayPackagesInternationalIndexRoute:
    HolidayPackagesInternationalIndexRoute,
}

const HolidayPackagesRouteWithChildren = HolidayPackagesRoute._addFileChildren(
  HolidayPackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  HolidayPackagesRoute: HolidayPackagesRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesCabsRoute: ServicesCabsRoute,
  ServicesFlightsRoute: ServicesFlightsRoute,
  ServicesForexRoute: ServicesForexRoute,
  ServicesHotelsRoute: ServicesHotelsRoute,
  ServicesInsuranceRoute: ServicesInsuranceRoute,
  ServicesVisaRoute: ServicesVisaRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
