-- Seed domestic destinations required for Word tour package imports

INSERT INTO public.destinations (slug, scope, name, region, image_url, blurb, highlights, sort_order)
VALUES
  ('madhya-pradesh', 'domestic', 'Madhya Pradesh', 'Central India', 'https://images.unsplash.com/photo-1593691509543-cb9612be4bb6?auto=format&fit=crop&w=1200&q=70', 'Holiday packages in Madhya Pradesh.', ARRAY['Mahakaleshwar Temple', 'Bandhavgarh Safari Kanha National Park', 'Khajuraho Temples', 'Bhedaghat Waterfalls'], 20),
  ('gujarat', 'domestic', 'Gujarat', 'West India', 'https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=1200&q=70', 'Experience Gujarat — a land of sacred temples, majestic wildlife, white deserts, serene beaches, vibrant culture, and iconic modern attractions.', ARRAY['Experience Gujarat — a land of sacred temples, majestic wildlife, white deserts,'], 21),
  ('uttar-pradesh', 'domestic', 'Uttar Pradesh', 'North India', 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=70', 'Discover Uttar Pradesh, the heart of India''s spiritual heritage, where sacred temples, ancient cities, Mughal monuments, wildlife and vibrant culture create unforgettable travel experiences.', ARRAY['Kashi Vishwanath Temple', 'Shri Ram Janmabhoomi, Ayodhya', 'Taj Mahal, Agra Triveni Sangam, Prayagraj Dudhwa National Park Mathura & Vrindav'], 22),
  ('lakshadweep', 'domestic', 'Lakshadweep', 'South India', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=70', 'Discover Lakshadweep, India''s hidden tropical paradise, where turquoise lagoons, coral reefs, untouched islands and serene beaches offer an unforgettable island escape.', ARRAY['Agatti Island', 'Bangaram Island Scuba Diving & Snorkeling Glass Bottom Boat Ride Sunset at Kadma'], 23),
  ('karnataka', 'domestic', 'Karnataka', 'South India', 'https://images.unsplash.com/photo-1596176530629-397b78511ed5?auto=format&fit=crop&w=1200&q=70', 'Discover Karnataka, a perfect blend of royal heritage, lush coffee plantations, scenic hill stations, pristine beaches, ancient temples and thrilling wildlife experiences.', ARRAY['Mysore Palace', 'Coorg Coffee Plantations Hampi UNESCO Heritage Kabini Wildlife Safari', 'Chikmagalur Hills', 'Gokarna & Murudeshwar BeachesExplore Our Karnataka Tour'], 24),
  ('maharashtra', 'domestic', 'Maharashtra', 'West India', 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=70', 'Experience the vibrant charm of Maharashtra, where bustling cities, scenic hill stations, sacred temples, pristine beaches and thrilling wildlife create unforgettable journeys.', ARRAY['Marine Drive', 'Gateway of India Mahabaleshwar Strawberry Farms', 'Shirdi Sai Baba Temple', 'Tadoba Tiger Safari'], 25),
  ('odisha', 'domestic', 'Odisha', 'East India', 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=70', 'Discover the timeless charm of East India with Odisha''s sacred temples, pristine beaches and rich heritage, combined with West Bengal''s colonial grandeur, Himalayan hill stations, tea gardens and vibrant culture.', ARRAY['Jagannath Temple, Puri', 'Konark Sun Temple', 'Victoria Memorial, Kolkata Howrah Bridge', 'Darjeeling & Tiger Hill Sunrise'], 26),
  ('west-bengal', 'domestic', 'West Bengal', 'East India', 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=70', 'Experience the cultural soul of West Bengal with colonial heritage, Himalayan hill stations, tea gardens, wildlife sanctuaries, pristine beaches and spiritual destinations.', ARRAY['Darjeeling & Tiger Hill', 'Victoria Memorial & Howrah Bridge', 'Sundarbans Mangrove Safari Dooars Tea Gardens & Rhino Safari', 'Digha & Mandarmani Beaches'], 27)
ON CONFLICT (slug, scope) DO NOTHING;
